# Generated by Django 5.1.3 on 2024-11-29 03:28

from django.db import migrations

def create_default_roles(apps, schema_editor):
    Role = apps.get_model('user_management', 'Role')
    roles = ['Superuser', 'Agent', 'Client']
    for role_name in roles:
        Role.objects.get_or_create(name=role_name)

class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_roles),
    ]
