# Generated by Django 5.1.3 on 2024-11-29 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_plan_clientdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('dropdown', 'Dropdown')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('choices', models.TextField(blank=True, help_text='Comma-separated values for dropdown/radio fields')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='user_management.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='user_management.client')),
            ],
        ),
    ]
