# Generated by Django 5.1.3 on 2024-11-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_clientformfield_clientresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientformfield',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clientdetails',
            name='url_path',
            field=models.SlugField(blank=True),
        ),
    ]
