# Generated by Django 5.1.3 on 2024-12-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_clientformfield_hidden_alter_clientdetails_url_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientformfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('dropdown', 'Dropdown'), ('star_rating', 'Star Rating')], max_length=20),
        ),
    ]
