# Generated by Django 5.1.3 on 2024-12-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_alter_clientformfield_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='duration_type',
            field=models.CharField(choices=[('days', 'Days'), ('months', 'Months'), ('years', 'Years')], default='Day', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='duration_value',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
