# Generated by Django 5.1.3 on 2024-12-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0008_plan_duration_type_plan_duration_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration_type',
            field=models.CharField(choices=[('hours', 'Hours'), ('days', 'Days'), ('months', 'Months'), ('years', 'Years')], max_length=10),
        ),
    ]
