# Generated by Django 5.1.3 on 2024-12-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_alter_clientdetails_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='url_path',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
